repos:
  - repo: https://github.com/PyCQA/bandit
    rev: master
    hooks:
    - id: bandit
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: master
    hooks:
      - id: flake8
  - repo: https://github.com/asottile/pyupgrade
    rev: master
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/asottile/reorder_python_imports
    rev: master
    hooks:
      - id: reorder-python-imports
        args: [--py38-plus]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: master
    hooks:
      - id: mypy
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: mixed-line-ending
      - id: pretty-format-json
        args: [--autofix]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
    - id: run-tests
      name: Run unit tests
      entry: pytest tests
      language: system
      additional_dependencies: [pre-commit, pytest]
      always_run: true
      pass_filenames: false
    - id: pylint
      name: pylint
      entry: pylint ./{{cookiecutter.project_slug}}
      language: system
      always_run: true
      pass_filenames: false
      types: [python]
